An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid bucket name "dev01-39591-abinitio-dev"": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
fatal: [localhost]: FAILED! => {"boto3_version": "1.17.112", "botocore_version": "1.18.6", "changed": false, "msg": "Failed while looking up bucket (during bucket_check) dev01-39591-abinitio-dev\".: Parameter validation failed:\nInvalid bucket name \"dev01-39591-abinitio-dev\"\": Bucket name must match the regex \"^[a-zA-Z0-9.\\-_]{1,255}$\" or be an ARN matching the regex \"^arn:(aws).*:s3:[a-z\\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\\-]{1,63}$\""}
